### ISSUE TITLE
Snap 1.0

### ISSUE THREAD

**Issue by LukeHoersten** [haskell-servant/servant-snap#1]
Please target snap 1.0. The main holdup for it's release are basically docs. It's 100% code coverage and use of io-streams are the main draw.

**Comment by imalsogreg** [comment]
Totally agree! here's the migration: 297eaf912ab6b0f22ad077ba16a78f47d531677a

Please let me know if you try this out.

**Comment by LukeHoersten** [comment]
I'll definitely try this out! Thanks for your work! A+

**Comment by imalsogreg** [comment]
Heh thanks. Just caught your convo on irc. If you go with Snap in your servant apps, I think it'd be interesting to have some snap specific combinators, and steal from servant-ede for a Heist media type.

**Comment by LukeHoersten** [comment]
Cool yeah. Have you talked to Doug? He may be interested in helping integrate a Heist front-end.

You should definitely let Greg Collins know too that you’ve made a servant back-end for it. Snap 1 is basically done and has been for quite a while with 100% code coverage but he doesn’t want to release it until all the docs are done etc (which I don’t even know if are being worked).

**Comment by imalsogreg** [comment]
Yep, Doug's interested in servant for sure! Type safety is kind of the missing puzzle piece in snap routing and query param handling, so servant fills that gap really nicely. Not sure he wants to spearhead a heist-servant effort but I'm sure he'd be a great help. I need that soon and will probably crank out a more or less blind copy of servant-ede.

**Comment by alpmestan** [comment]
Feel free to bug me as well for any explanation / brainstorming on the servant side of things. I would **love** for this servant-snap effort to become a first-class citizen in the servant ecosystem!
