### ISSUE TITLE
readme doc error: serveSnaplet(not httpServe) for running SnapletInit

### ISSUE THREAD

**Issue by clojurians-org** [haskell-servant/servant-snap#28]
for [More detailed Snap example] section in Readme doc:
it should use serveSnaplet (not httpServe) to serve snaplets, 
```haskell
main :: IO ()
main = httpServe defaultConfig app
```

**Comment by imalsogreg** [comment]
Thanks, good catch! Closed by 5ed901641c99519fa3e0c701cb430dbb8f6f1b5c
