### ISSUE TITLE
Error in stack build.

### ISSUE THREAD

**Issue by wpoosanguansit** [haskell-servant/servant-snap#9]
I do have stack installed and run successfully.  However I do run into issue doing as instructed in the readme.md

This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      snap: needed (>=1.0 && <1.1), couldn't resolve its dependencies
    needed for package hspec-snap-1.0.0.0

--  Failure when adding dependencies:
      snap: needed (==1.0.*), couldn't resolve its dependencies
      snap-server: needed (==1.0.*), couldn't resolve its dependencies
    needed for package servant-snap-0.6

--  Failure when adding dependencies:
      snap-server: needed (>=1.0 && <1.1), couldn't resolve its dependencies
    needed for package snap-1.0.0.0

--  Failure when adding dependencies:
      clock: needed (>=0.4.1 && <0.5.2), 0.6.0.1 found (latest applicable is 0.5.1)
    needed for package snap-server-1.0.0.0

Is there anything else that is needed to be done before the build?  Thanks for your help.

**Comment by imalsogreg** [comment]
Thanks for the report. I think if we want stack to work for this project, we will need to point stack.yaml at the newly-released-to-hackage snap packages.

@sigrlami is this an easy thing for you to implement? I don't use stack myself so I wouldn't want to put up a bad patch for the stack.yaml file.

**Comment by sigrlami** [comment]
@imalsogreg sorry for a long reply,  I'm using stack successfuly with master branch for couple of months 
@wpoosanguansit please share you stack.yaml so I can investigate

**Comment by sigrlami** [comment]
@wpoosanguansit added PR, with latest updates, you can build with stack again

**Comment by wpoosanguansit** [comment]
Thanks for your help.  I will try it now.

**Comment by wpoosanguansit** [comment]
I remember stack ghci used to work.  But I do get this error now:

The main module to load is ambiguous. Candidates are:
1. Package `servant-snap' component exe:snap-greet with main-is file: /Users/w.poosanguansit/Desktop/Projects/Haskell/servant-snap/example/greet.hs
2. Package `heist' component exe:benchmark with main-is file: /Users/w.poosanguansit/Desktop/Projects/Haskell/servant-snap/.stack-work/downloaded/_8_14lV9tQlk/test/suite/Benchmark.hs
You can specify which one to pick by:
 * Specifying targets to stack ghci e.g. stack ghci servant-snap:exe:snap-greet
 * Specifying what the main is e.g. stack ghci --main-is servant-snap:exe:snap-greet
 * Choosing from the candidate above [1..2]
* * * * * * * *

Specify main module to use (press enter to load none):
Not loading any main modules, as no valid module selected

Configuring GHCi with the following packages: servant-snap, servant, io-streams-haproxy, heist, snap-loader-dynamic, hspec-snap, snap-core, snap-loader-static, snap-server, snap
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help

/Users/w.poosanguansit/Desktop/Projects/Haskell/servant-snap/src/Servant/Server/Internal.hs:11:14: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS

/Users/w.poosanguansit/Desktop/Projects/Haskell/servant-snap/.stack-work/downloaded/HHWQO61NVGEM/servant/src/Servant/API/Capture.hs:24:30:
     error: unterminated /* comment
-- >>>            -- GET /src/*
                             ^
1 error generated.
phase `C pre-processor' failed (exitcode = 1)

<no location info>:
    Could not find module ‘Control.Concurrent.Extended’
    it is a hidden module in the package ‘snap-server-1.0.0.0@snaps_2tNYHY7tout8pEI2oP7P1b’

**Comment by sigrlami** [comment]
@wpoosanguansit are you using Windows?

**Comment by sigrlami** [comment]
with stack you need to forward some options, look https://sigrlami.eu/en/content/notes/run-snap-interactive.html for guidance

**Comment by wpoosanguansit** [comment]
I am using Mac Elcapitan.  I remember that stack ghci used to just work in the old setup without specifying anything extra.  But I will take a look and see if I can put something into stack to make it work.  Thanks again.

**Comment by sigrlami** [comment]
@wpoosanguansit update stack to latest git version, just checked running interactive mode also ok

**Comment by sigrlami** [comment]
This is clearly stack error, I use ghci like this (as suggested earlier)
```
stack ghci --ghci-options "-XTemplateHaskell -XTypeFamilies -XOverloadedStrings -XCPP" servant-snap
```
then to load example
```
:load example/greet.hs
```
just `stack ghci` never worked without problems for me on complex projects

**Comment by wpoosanguansit** [comment]
Thanks for your help.  This works.

**Comment by imalsogreg** [comment]
@sigrlami Thanks so much for the excellent stack help!
